livereload: true
port: 8000
open_url: true
strict_front_matter: true

source: src
destination: dist

timezone: America/New_York
url: https://docs.katsute.dev

exclude:
  - /CNAME
  - /LICENSE
  - /README.md

sass:
  load_paths:
    - dependencies/katsute/css
  style: compressed