name: Improve Documentation
description: Make a suggestion to improve existing documentation
labels: [feature request, documentation]
assignees: []
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Prerequisites
      description: |
        *If **all** checks are not passed then the issue will be closed.*
      options:
        - label: I have checked that no other similar issue already exists.
          required: true

  - type: input
    id: link
    attributes:
      label: Link
      description: |
        Which page should be improved? (please provide a link)
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: Suggestion
      description: |
        Which parts of the page should be improved?
    validations:
      required: true