name: Improve Site
description: Make a suggestion to improve the site
labels: [feature request, website]
assignees: []
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Prerequisites
      description: |
        *If **all** checks are not passed then the issue will be closed.*
      options:
        - label: I have checked that no other similar issue already exists.
          required: true

  - type: textarea
    id: info
    attributes:
      label: Suggestion
      description: |
        What changes should be made to the site?
    validations:
      required: true